[project]
name = "pizzadeliveryapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-users>=15.0.4",
    "passlib[bcrypt]>=1.7.4",
    "sqlmodel>=0.0.34",
]
